language: java

matrix:
   fast_finish: true

install: true

# avoid uploading the cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
    - jdk_switcher use oraclejdk8
    - ./gradlew release -Dedgent.build.ci=true
###    - ./gradlew test -Dedgent.build.ci=true
###    - ./gradlew test --continue -Dedgent.build.ci=true
    - ./gradlew test7Compile -Dedgent.build.ci=true
    - jdk_switcher use oraclejdk7
###    - ./gradlew test7Run -Dedgent.build.ci=true 
    - ./gradlew test7Run --continue -Dedgent.build.ci=true 
